version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: test

  test:
    cmds:
      - go test ./...

  build:
    cmds:
      - go build rag.go

  build-linux:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build rag.go
