version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: test

  test:
    cmds:
      - go test ./...

  sync:
    cmds:
      - uv sync

  build:
    cmds:
      - go build ./cmd/rag
