version: "3"

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build ./cmd/ragctl

  build-linux:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build ./cmd/ragctl
